language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: spvn0l1ftexBeDj/POzb0PDp67JoXWIwDWnVOA+qRuMZs/Lf4gNgPAZBoSmNQs/LHyz4u77wxBTsZS97lgjGaqwR0PEfGcq35I9YIEeftiUSdwNvK6I+uBtV6BQbbPB7Qx6u47nFQUZDeWsu9ThWSYhRZZNK8OtIKBQC6lXR4TAUUKueUtao+0MnmOPKB3jkKKVFoXi3a1u104PJi6uCleR3sWwEBHqy60AaxqNxvhcuoBCjfosP74qIFQ8kLjYnna6Cz0LZeFVZrgyDBUDFNbzeF0WHCHOcjm5CscGjckQRb+2apxF8fflarXaoaV5UCDLh5KJXXUz/74u7620IKexcyhaqYJQnctU6yxwS+sWXgHU22UT2xW2fqDsYvhG8nbBMInrNB1u4F20jGlC/Wrt51F1CzXSZz1pxIPvwWObzBl9JxKG35FCgZlC1raowG1yekSTAvuUvgPTk3bSiPM38XD7okI/IuDdyUK2G8aRsgDN5Yuu7n8lNVBLEjXfF0IaFPsP6VHEy3UkOn75epwmTRsCLyBRDQgQMK1lCo738QJywFkoHECUCC9ABPgz3Ch16DhIg0Cz1sZTjAG43HCFRLBtL09MmjnGhQZoUrphXN3sGUeJDcENHV+zfZmJzbR0a+kZWBeQcCN/sRjXea175ZDyA1sJFR3pky42psZ0=
  app: mighty-ocean-33627
  on:
    repo: manish237/project-capstone-2
